FROM centos:centos7
LABEL maintainer Chris Collins <collins.christopher@gmail.com>

LABEL name "mongodb"
LABEL version "1.0"
LABEL release "1"
LABEL summary "Community Honey Network mongodb container"
LABEL description "MongoDB is an open-source, document database designed for ease of development and scaling"
LABEL authoritative-source-url "https://github.com/CommunityHoneyNetwork/mongodb"
LABEL changelog-url "https://github.com/CommunityHoneyNetwork/mongodb/commits/master"

ENV playbook "mongodb.yml"

RUN yum install -y epel-release \
      && yum install -y ansible

RUN echo "localhost ansible_connection=local" >> /etc/ansible/hosts
ADD . /opt/
RUN ansible-playbook /opt/${playbook}

EXPOSE 27017

ENTRYPOINT ["/sbin/runsvdir", "-P", "/etc/service"]


