---
  mongo_apt_keyserver: hkp://keyserver.ubuntu.com:80
  mongo_apt_id: 0C49F3730359A14518585931BC711F9BA15703C6
  mongo_apt_repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse

  mongo_yum_baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
  mongo_yum_gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc

  runit_rpm_src: https://github.com/CommunityHoneyNetwork/rpmbuilder-runit/releases/download/2.1.2-1/runit-2.1.2-1.el7.centos.x86_64.rpm

  mongo_pkgs:
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools

  mongo_runit_service_dirs:
    - /etc/service/mongodb
    - /etc/service/mongodb/control
